### ISSUE TITLE
ng-grid doesn't update data

### ISSUE THREAD

**Issue by batuuu** [angular-ui/ui-grid#1302]
http://stackoverflow.com/questions/24791142/ng-grid-doesnt-update-data

**Comment by ChristopherMeek** [comment]
I'm seeing the above problem too.  I've also tried  calling notifyDataChange('all') and refresh() but the rows inside the gird always maintain the original set of rows given - not the new set of rows.  The original plunkr still demonstrates the issues I think.

**Comment by rlgod** [comment]
Any progress on this issue. I've run into the same difficulty where re-assigning ```$scope.gridOptions.data``` does not cause the grid to refresh. I can log and see that the underlying data is changing correctly.

**Comment by PaulL1** [comment]
a) comments on closed issues can easily get missed.  If the issue is closed that usually means we think it is resolved
b) what version are you using - ng-grid or ui-grid?
c) usually the problem is one of pointers and objects - if you assign your data as `$scope.gridOptions.data = myData`, the grid will grab a pointer to that data.  If you later do `$scope.gridOptions.data = myOtherData`, you've changed here $scope.gridOptions.data is pointing, but the grid still has a pointer to the old object.  You need to either use:
```
  $scope.data = myData;
  $scope.gridOptions.data = 'data';
```
or you need to empty and refill the original array:
```
  $scope.gridOptions.data.length = 0;
  angular.forEach( $scope.myOtherData, function( row ) {
    $scope.gridOptions.data.push( row );
  });
```

**Comment by rlgod** [comment]
a) Woops
b) ui-grid 3.0.0 rc-16
c) I tried both your suggestions to no avail. I can't even get it to change when I zero the length of the array stored in ```$scope.gridOptions.data``` (I can see the array stored there is empty when I log it to console)

**Comment by PaulL1** [comment]
Changing the data should just work - it's in one of the tutorials (sorry, away from my computer and can't remember which one). 

What is it exactly doing?  Do you have data and its displaying, then you change it and no update?  Could you provide a plunker (perhaps based on the tutorial)?

**Comment by PaulL1** [comment]
The tutorial is: http://ui-grid.info/docs/#/tutorial/112_swapping_data

**Comment by apueee** [comment]
I'm also getting same problem. It's not updating ... I tried with different way nothing work so far. Any progress on this issue?

**Comment by PaulL1** [comment]
The issue is closed on the basis that it works in the tutorial.  So unless you have a plunker demonstrating a problem, the assumption is it's a problem in your code not a ui-grid issue.

**Comment by goleafs** [comment]
I have this issue with editing a row.column value
That is not covered by the tutorial.

I tried resetting the data instead, but that does not work either same as the others.

**Comment by nonmanifold** [comment]
issue occures when new data has exactly same length as the old. I'm working on PR to fix that.
It's because dataWatcher() is set to watch only for pointer or array length changes.

**Comment by PaulL1** [comment]
@goleafs: if you edit a row.column value you may need to use `notifyDataChange`

**Comment by totszwai** [comment]
Using $scope.$apply() works in your example posted on Sep 7, 2014.
But it won't refresh without calling apply.

**Comment by nonmanifold** [comment]
To whom may also came here frustrated:
ngGrid won't update if you edit-in-place your data array by overwriting data array members so that the length stays the same. NgGrid  watches on array pointer and on its length, so just replace array with new one each time you recive data. 
1) $scope.data=[{row1...}, {row2...}]; //render inital data
2) update $scope.data:
$scope.data.length=0; //or splice
$scope.data.push(row1a);
$scope.data.push(row1b);
3) here we have ngGrid options resolving to same array with the same length, so grid think that nothing changed.
To overcome this, just replace $scope.data with new one.

**Comment by thanhlcm90** [comment]
My solution:
$http.get('url').success(function(res) {
// clear data
gridOptions.data.length = 0;
// update data in next digest 
$timeout(function() {
    gridOptions.data = res;
});
});

**Comment by pompiamp** [comment]
In my case I had a Json string (myDataStr) assigned to gridOptions.Data. 
What worked for me was to assign an object instead of an string by doing JSON.parse(myDataStr) and now it Works!

**Comment by totszwai** [comment]
Guys, actually, i believe you can now use the auto resize module. I was doing something else, and was using the auto resize plugin, and the grid refresh/resize itself after I set the data WITHOUT CALLING $APPLY()

:O

**Comment by mgrivera** [comment]
@totszwai  What is auto resize plugin?? ...

**Comment by totszwai** [comment]
@mgrivera http://ui-grid.info/docs/#/tutorial/213_auto_resizing

**Comment by mgrivera** [comment]
@totszwai thanks ...

**Comment by FlorisSteenkamp** [comment]
Going on a comment by nonmanifold, I fixed the issue within ng-grid source code. In the minified version search for "d.$on("$destroy",d.$parent.$watch(p.data,t))" and replace with "d.$on("$destroy",d.$parent.$watchCollection(p.data,t))".

Or, in the debug version search for "$scope.$on('$destroy', $scope.$parent.$watch(options.data, dataWatcher));" and replace with "$scope.$on('$destroy', $scope.$parent.$watchCollection(options.data, dataWatcher));"

The $watchCollection() function will watch for a (shallow) reference change on any of the items in the data array, including if items are added or deleted from the array and NOT ONLY ARRAY LENGTH CHANGES.

**Comment by ravenscar** [comment]
Also been having this problem in 3.0.0-rc.22 with angular 1.3.17

It seems this fix by @FlorisSteenkamp, or something like it, is in the code by rc.22. If the `fastWatch` option is set to false (default) it seems to now do a `$watchCollection` instead of `$watch`.

However...

If you replace your grid's data object with another it now uses hashing by default to detect changes and if you haven't provided your own hashing function it just uses row.$$hashKey.

So if row.$$hashKey of the new row matches $$hashKey of an old row, even if the object is different, it won't replace the row or update anything.

But why, you ask very sensibly, would the $$hashKey of a new row match the old? Surely they didn't use a hash of such a small value it could repeat, that would be mad! Is this why my rows aren't updating?
 
Well yes, and no. It seems the hash will repeat every 46656 rows, so if you have more rows than this expect problems.

For me the problem was that the objects representing each row in the data had been silently augmented with $$hashKey. I would then clone the grid's data to a new object, modify it, then reassign it to the grid's data object again. Ng-grid would then inspect the rows and detect that since the $$hashKey (which had been cloned along with the rest of the data) was the same, the row must be the same, irrespective of the values within it.

solutions: 
set option `enableRowHashing` to be false (trivial fix but might be bad for performance)
OR
set option `getRowIdentity` to be function returning an appropriate hash (might be difficult and/or bad for performance)
OR
delete the $$hashKey on any object which you've cloned and are placing back into the grid's data object (might be tricky to track down all the places but should be fast)

**Comment by NenadP** [comment]
It is still occurring - ui-grid - v3.0.0-rc.21 - 2015-04-28.

Most simplistic solution is to do, as @thanhlcm90 suggested:

```javascript
	$scope.gridOptions.data = [];
	$timeout(function() {
		$scope.gridOptions.data = $scope.data;
	});
```

but is not nice ;) as, for example, I lose row selection and need to do work to restore the selection :(

**Comment by c0bra** [comment]
@ravenscar oh wow; well that's an interesting edge case you've found :)

If we make the hashkeys one character longer it would handle 1.68 mil rows. That should be OK, right? :)

**Comment by treyhoover** [comment]
Any updates on this? @thanhlcm90's suggestion was the only thing that worked for me as well, but I agree with @NenadP that the flicker and lost context is a pain.

**Comment by nbsynch** [comment]
I ran into this when I was nesting the grid in a Boostrap tab created by the Angular directives for Bootstrap.  If I pulled the grid outside of the tab it would refresh, if I left it in the tab it wouldn't until I did something like resize my browser window.  I reworked my layout to avoid the tabs, didn't get to try the solutions other people have posted.

**Comment by wesleycho** [comment]
@nbsynch running into the same issue at work I think, and I have been leading UI Bootstrap development for the past half year :( .

This issue is quite perplexing to me - it only happens on first page load. If I navigate to another state (UI Router) and come back, the data populates properly. As far as I can tell, there might be a race condition involving the compilation/linking of the directives in ui grid. I have some more investigation to do, should have more details over the next couple of days.

**Comment by wesleycho** [comment]
Doing some further investigation, what seems to be happening is that the data gets set properly at some point, but `self.rows` is an empty array at that stage, so on next call to `self.processRowsProcessors(self.rows)` in `Grid.prototype.refresh`, the empty array then incorrectly replaces the existing rows. `self.rows` is incorrectly set to length of 0 in `Grid.prototype.modifyRows`, which is marking the array to be cleared.

The `dataWatchFunction` function is calling `grid.modifyRows` - I am setting the grid options data array to be an empty array at first, so what looks like is happening here is there is an incorrect reference with the watcher in the uiGrid directive if you destroy the reference to the data array by overwriting it. A suitable workaround for now is to never overwrite the array reference in `gridOptions.data` and to manually manage the array by clearing it and then populating the array.

Example:
```js
while (gridOptions.data.length) {
  gridOptions.data.shift();
}

Array.prototype.push.apply(gridOptions.data, newData);
```

This took me two days to figure out :( .

**Comment by DioNNiS** [comment]
Data update properly working properly since 3.0.7. For me 3.0.6 - works fine.

**Comment by dlypka59** [comment]
If the grid in in a div which is NOT in the same controller div parent which contains the control on whose event is causing some data in the grid to change, then I found that the grid will NOT update. The solution is to place the grid under the same controller parent div as the control causing the data change. So just keep the grid 'close' to the controls which cause data changes.

**Comment by isayo** [comment]
I have a similar issue, what I needed was I need to update a row in a model.
 so I removed the row and added it back on to the gridOptions data ..works for me.Hope it helps

  <span stop-event='click' ng-click="grid.appScope.edit(grid, row)">
        <span class="glyphicon glyphicon-edit" title="Edit"></span>
</span>
      

           var index = $scope.gridOptions.data.indexOf(row.entity);
            $scope.gridOptions.data.splice(index, 1);

            $scope.gridOptions.data.push({
                "name": user.name,
                "alias": user.alias,
                "phone": user.phone,
                "email": user.email,
                "active": user.active,
                "id": data.id
            });

**Comment by Alhuck** [comment]
None of the above solution works for me!!!! Ui - grid is not refreshing the data which comes from ajax request(particularly while calling the search when selecting the  date using the ui-datepicker as a filter).
In debugger, `$scope.gridOptions.data` comes as a `string`('data'), so if i apply any copy or other things to it, its throwing console error. Help me Folks

Thanks,

Alhuck

**Comment by dlypka59** [comment]
If your button is <input type="submit">, that will complete the postback
and tear down the page *before* the ajax can return its result So use
<input type="button">.  Also make sure the grid is under the same parent
<div> as any control that causes and update of the grids data.

**Comment by Alhuck** [comment]
No i don't have any button, the filterchanged event is triggered once i set the filter model when i select the date from ui-datepicker. Response comes as expected and i am updating the ui-grid data on ajax success callback but its not updated with the ui-grid(with infinte scroll).

**Comment by stoplion** [comment]
+1  Having same problem

**Comment by dlypka59** [comment]
Try moving the ng-controller tag to a div which for sure encloses the ui
grid's div.
Make sure within the ajax success that you are calling
$scope.$apply(function to update all data in the $scope.data for the grid)

On Wed, Dec 16, 2015 at 11:28 PM, George C. Norris <notifications@github.com

**Comment by prettycode** [comment]
So here's something that is confusing me, and probably others.

When I first create a `ui-grid` using only `ui-grid="{ data: myComponent.myTableData }"`, the grid automagically figures out the columns to create (awesome).

However, later, when my data has changed, and I update the value of `myComponent.myTableData`, the `ui-grid` doesn't automagically create the `columnDefs` like it did when the table was first populated. Instead, it keeps wahtever `columnDefs` it used when the grid was first created.

When `myComponent.myTableData` changes, I don't know what the new columns will be&mdash;I want `ui-grid` to automagically figure them out again.

Is there an example of how to do this&mdash;force the `columnDefs` to automagically be regenerated when `data` changes?

**Comment by ricardocabral** [comment]
Definitely a bug causing data not to be refreshed on the grid if the remotely updated data has the same length as the displayed data.

Clearing the scope var holding the data (the one referenced on `gridOptions.data`) and then setting it again with the remote data on $timeout worked for me:

```
                $scope.cadastros = [];
                $timeout(function () {
                    $scope.cadastros = cadastros.data;
                });

```

**Comment by gaurav789** [comment]
After struggling for almost 1 day, I found a very simple solution to this issue.
In suceess function of your ajax call just use this piece of code.

```
Service.GetData(param).then(function (data){
 $scope.gridOptions.data.length = 0;
                $scope.columns = [];
                for (var property in data[0]) {
                    if (data[0].hasOwnProperty(property)) {
                        $scope.columns.push({name : property});
                    }.
 $scope.gridOptions.columnDefs = $scope.columns;
  }
```

This should get you going.

**Comment by jonathanboswell** [comment]
@PaulL1 @c0bra Hey Paul & Brian, I put a Plunker together which shows the problem:
https://plnkr.co/edit/xDhUDY44PDF54CrtWmjX?p=preview

I think @dlypka59 might be right about the issue arising when in a child controller...

**Comment by Nodarii** [comment]
Hello all, 

I've spent a lot of time on this issue and glad to say that I found some solution

```javascript
this.$timeout(() => {
    this.$scope.gridOpts.virtualizationThreshold = data.length;
    this.$scope.gridOpts.data = data;
});
```
Would be cool if it will help someone like me:)

**Comment by Ruud-cb** [comment]
@Nodarii That is bad for performance, when having about 1000 records.
Anyway I'm still dealing with this issue, As I want the best solution, not some kind of hack like removing/adding an item. The application is realtime so updates are coming in regularly. (Hard to plunker). 
I wonder why no one mentioned `self.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ROW);`. I've tried to call that as well after every update. doesn't seem to work :(

**Comment by neuralbrain** [comment]
This is my fix and it works:

            var requestData = null;
            var onGetSuccess = function (response)
            {
                if (requestData)
                {
                    $scope.data = response.data;
                    $scope.gridOptions.data.length = 0;
                    $timeout(function ()
                    {
                        $scope.gridOptions.data = response.data;
                        $scope.$apply();
                    });
                }
                else
                {
                    $scope.gridOptions.data = response.data;
                }
                requestData = response.data;
            };

**Comment by neuralbrain** [comment]
The above fix is for ui grid

**Comment by marscode-cn** [comment]
give different id can refresh grid data
`	$scope.gridOptions.rowIdentity = function(row) {
		return row.id + new Date().getTime();
	};
	$scope.gridOptions.getRowIdentity = function(row) {
		return row.id + new Date().getTime();
	};`

**Comment by veica** [comment]
@ravenscar solution
 enableRowHashing:false
works well for me, but I am scared what does it mean it might be bad for performance.

**Comment by ravenscar** [comment]
@veica I think if you are concerned with the performance then instead I would delete $$hashKey on any object when you modify it.

**Comment by Shellnut** [comment]
For those of you who were using Ui Bootstrap's uib-tabs to swap the data and experiencing buggy behavior, I was able to make a work around using an adaptation of the [demo code](http://ui-grid.info/docs/#/tutorial/112_swapping_data) and bootstrap css.

Plunker with working behavior (bootstrap css): [http://plnkr.co/edit/IRjelO?p=preview](http://plnkr.co/edit/IRjelO?p=preview)
Plunker demonstrating buggy behavior (uib-tabset): [http://plnkr.co/edit/Kd26Dr?p=preview](http://plnkr.co/edit/Kd26Dr?p=preview)

**Comment by dlypka59** [comment]
Great idea.
Just what I need.
Many thanks.

**Comment by mportuga** [comment]
Closing old issues.

**Comment by troiza** [comment]
@PaulL1 
Same as in tutorial not working with modified data. Try to swap  
http://plnkr.co/edit/RMFHpFwm90IEDKiIaUrR?p=preview
Only columnsDefs changed properly, but data not

**Comment by Daniel5000** [comment]
yo tenia el mismo problema, pero aquí encontré un buen ejemplo: http://embed.plnkr.co/99GO3k/preview.

En mi caso retornaba un objeto json desde el servidor, y cuando llegaba al navegador era un prototype Object y no un Prototype Array().

Mcuhas Gracias
