### ISSUE TITLE
Scrolling - column headers misaligned with data...

### ISSUE THREAD

**Issue by cleon26** [angular-ui/ui-grid#2592]
Hey guys.  I found a weird issue.  I've been scratching my head with this one for a while trying to narrow it down.  As best I can tell it's somehow related to the container size?
1. Run this plnkr.
2. Reduce the width of the right most column to about the size of the label "Company".  
3. Scroll the table to the right and everything looks fine.
   http://plnkr.co/edit/2gUnkzVdF1xvU9muNZ4K?p=preview
4. Now run the plunker in embedded view.
5. Reduce the width of the right most column to about the size of the label "Company".  
6. Scroll the table to the right and notice that the columns are misalgined with the headers.
   http://embed.plnkr.co/2gUnkzVdF1xvU9muNZ4K/preview

![normal](https://cloud.githubusercontent.com/assets/7850944/5807791/b06b3250-9ff4-11e4-8c8f-36fcf256d119.png)
![embedded](https://cloud.githubusercontent.com/assets/7850944/5807792/b3ed52dc-9ff4-11e4-9793-ca30ee6f0c31.png)

**Comment by kjkurtz** [comment]
I have this same issue except it only occurs when horizontal scrolling. It initially shows up correctly.

**Comment by alexandery** [comment]
I could swear I've added an issue for this last week but I cannot find it anywhere?! Yeah, seems like there is some issue with the scrolling and the header getting out of sync with the columns.

**Comment by PaulL1** [comment]
There was, I think, but I haven't recreated any issues with header misalignment for some time (since @swalters removed the throttling I think).  On the plunkers provided above I don't get a misalignment, so perhaps it is somewhat OS or browser dependent?

**Comment by alexandery** [comment]
@PaulL1 I get it on both IE9 and FF 35 (whatever is the latest as of today). And I do get it on Tutorial pages.

P.S. Funny enough - I submitted an issue for this mid last week but for the life of me cannot find it in the issues here. I had screenshots to showcase the issue. Weird.

**Comment by cleon26** [comment]
I can replicate it on IE11 and FF35.
And I swore that I could do it in Chrome39 yesterday as well, but am starting to doubt myself this morning.

**Comment by PaulL1** [comment]
I'm trying to replicate today, and I cannot replicate on firefox on Linux, nor on Chrome.  

When you say you scroll, is there some trick to the scrolling?  I've tried trackpad on Chrome/OSX, and I've tried both dragging and using the scrollbar buttons on Firefox, neither are giving me a header misalignment.

**Comment by cleon26** [comment]
Nothing fancy...  I can try again at work on Monday...

**Comment by cleon26** [comment]
Just tried again this morning and can still replicate it in FF.  Doesn't seem to matter whether I click the scroll button or drag the scroll bar.

![image](https://cloud.githubusercontent.com/assets/7850944/6003608/ef3eb872-aaca-11e4-8791-dbe161aa848c.png)

**Comment by sachinny21** [comment]
I am running into similar issues, tested in both IE11, FF30

**Comment by yugansh20** [comment]
Hi I am facing same issue.
When we scroll to the extreme right some of the columns are not reachable.
It will show 2nd last or 3rd last column as last column and I can see a very small part of the last column

**Comment by PaulL1** [comment]
@yugansh20 : your issue sounds different, this issue is about the header being misaligned with the column, not columns being unreachable.  If that is your issue, suggest raising that as a new issue along with a plunker that demonstrates it.

**Comment by sachinny21** [comment]
any updates to this hi-pri bug?

**Comment by dczepierga** [comment]
I write quick fix for scroll here:
https://github.com/angular-ui/ng-grid/issues/2734#issuecomment-74475177

Maybe this fix also help with this bug? (for me it works)

**Comment by c0bra** [comment]
This is a dupe of #2521, leaving open.

**Comment by c0bra** [comment]
Closed via cf86090

**Comment by sachinny21** [comment]
So a fix was made to align the column lines with the header lines but in the process a gap was introduced at the beginning of the grid...
![alignmentnewerror](https://cloud.githubusercontent.com/assets/9724198/6235497/dda90864-b6b0-11e4-9858-0b95fec46c99.png)

**Comment by Skinner927** [comment]
+1 I have the same issue as @sachinny21 

Is there another issue open to follow this?

**Comment by susharma-equinix** [comment]
Am not able to scroll the headers i.e. when i use horizontal scrolling only data get scrolled and not the header of the table.

Can some one please help this is quite high priority for us as of now.

**Comment by kicsisimo** [comment]
I have the same issue with rc22. Basically as @susharma-equinix  wrote only the content is scrolled but the table headers remain unchanged.

Any help?

**Comment by benbynum** [comment]
+1

**Comment by nitoloz** [comment]
This seems to reproduce even with the quite new release (3.0.7)
See image attached. Looks like the place the scroll takes is not counted when scrolling.
![scroll](https://cloud.githubusercontent.com/assets/7154361/10636896/d7b77846-7802-11e5-9538-0bf34b1727d0.png)

**Comment by dlypka59** [comment]
Workaround: Specify odd-valued % width for each column. Adjust the odd values up/down little by little until desired alignment is achieved. So my guess is that there is a round bug in the grid logic.
Example:
      { name: 'EMP_ID', displayName: 'Emp Id', enableCellEdit: false, width: '13%' },
      { name: 'EMP_NAME', displayName: 'Emp Name', enableCellEdit: false, width: '19%' },

Even width values such as 14% and 20% appear to aggravate the bug.

**Comment by nighojkarv** [comment]
I'm having the same issue but the other way. The left end of my grid is misaligned but as I scroll to the right, the grid gets aligned automatically. 
![grid-trouble](https://cloud.githubusercontent.com/assets/11322165/11670300/1182a13a-9dcf-11e5-9a4e-f3bde44f3e5b.png)

**Comment by dlypka59** [comment]
I solved it by not use % values for the column widths. Just use integer
units. Then the alignment is OK all the way on the scroll.

**Comment by nighojkarv** [comment]
I am using a fixed width of 150 on the columns, but still i'm getting the same issue.

**Comment by dlypka59** [comment]
remove any template in each column definition. The template if it is not
conforming to the various latest template standard can cause issues)

**Comment by kalihos** [comment]
I have the same problem...

![image](https://cloud.githubusercontent.com/assets/16207616/14451314/780a4dbc-0086-11e6-945c-dacec0c712d5.png)

I'm not using percentages nor templates, except one for color choosing. I saw in other thread the same problem, caused by using enableHorizontalScrollbar:2 (not my case: I'm using value 1). I'm using Angular 1.4.9 and UI-Grid 3.0.7, with the latest Chrome version.

**Comment by angular-git-user** [comment]
Yes @dlypka59 it seems that % in not working anymore.... If we create column defs and do not add width property, then it is properly aligned within firefox but not in chrome. So I created my own col defs and plugged in width in pixels `(ex. [{field:name, width:'100'}])` and it works fine.. (also tried with `%` but does not seem to allign, `(ex. [{field:name, width:'15%'}])`)

**Comment by SuprasannaBhaumik** [comment]
@nighojkarv , for your issue add this css rule in your custom class
.ui-grid-row{
	clear: both;
}

**Comment by kalihos** [comment]
Hi!

Thanks for your reply. I tried your solution, but I've not been capable to
make it work. But it's possible that it were my fault, because my css
knowledge is very limited. I tried to include your code inside the "myGrid"
css tag, as I make with others. But I can't get it fine. I noticed that
other similar grid works correctly, so I think there can be another
problem. Thank you again!


2016-08-26 6:03 GMT+02:00 SuprasannaBhaumik <notifications@github.com>:

**Comment by robs15** [comment]
![gridcrop](https://cloud.githubusercontent.com/assets/10429704/18631501/ffd58432-7e8f-11e6-876d-629bd6497ed0.gif)

I still have this issue on ver. 3.2.7.

Using the following options :
exporterMenuPdf: false,
        enableRowSelection: true,
        enableRowHeaderSelection: false,
        multiSelect: false,
        enableSorting: true,
        enableFiltering: true,
        //enableGridMenu: true,
        enableColumnResizing: true,
        enableHorizontalScrollbar: true,
        enableVerticalScrollbar: true,
        paginationPageSizes: [10, 20, 30],
        paginationPageSize: 10,

The columns are set to pixel widths. No width or height style set to the overall grid.

**Comment by mesutd0nmez** [comment]
Hey guys, i had same problem. I searched a code like below, and it worked for me. Try it.

.ui-grid-header-cell {float: left;}

**Comment by antonio91kim** [comment]
Hope everyone can solve this problem with this tip.
my idea is making an empty box beside last column header.
Assume that scroll width is 20px.
And add below lines on style sheet.

```
.ui-grid-header-cell.include-scrollbar:last-child .ui-grid-cell-contents {
  margin-right: -20px;
  padding-right: 20px;
}
```

**Comment by ginz** [comment]
@mesutd0nmez That works!

**Comment by kenaths** [comment]
Set enableVerticalScrollbar to true, It'll fix the issue.

            $scope.gridOptions = {
                enableVerticalScrollbar: 1,
                ..............
            }

**Comment by prashasti4** [comment]
I Fixed it by rounding of the header column min and max width in following function:
r.prototype.getColClassDefinition = function() {   
//round of the values
                return " .grid" + this.grid.id + " " + this.getColClass(!0) + " { min-width: " + Math.round(this.drawnWidth) + "px; max-width: " + Math.round(this.drawnWidth) + "px; }"
            }

**Comment by FizzBuzz791** [comment]
This is still an issue in version 4.6.0
I had to fix it by using @kenaths approach... Should not be necessary.

**Comment by kalihos** [comment]
That approach doesn't work for me (AngularJS 1.6.1). Still misaligned...

**Comment by kalihos** [comment]
Closed? Why? It doesn't work well...

**Comment by mportuga** [comment]
This was closed by a pull request that just got merged in. It will be in the next release of ui-grid
