### ISSUE TITLE
Scrolling performance is degraded

### ISSUE THREAD

**Issue by acheshire-scottlogic** [angular-ui/ui-grid#3277]
Since upgrading from RC-16 to RC-20 there has been a notable deterioration in scrolling performance. When scrolling there is a delay while the grid updates the rendered rows so you see blank space while scrolling.

We've adapted http://ui-grid.info/docs/#/tutorial/190_large_dataset in plunkr to use RC-16 and RC-20
RC-16: http://plnkr.co/edit/b3b6ItNdFUNwSHnnFOkE?p=preview
RC-20: http://plnkr.co/edit/643bsApNdJd5TavOdg4L?p=preview

You can see the performance difference in these videos.

RC-16: https://youtu.be/JMZbNpZRyu4,
RC-20: https://youtu.be/_1wM4_Y-Zes

Could it be that this is caused by the watcher count roughly doubling between these two examples from 660 in RC-16 to 1127 in RC-20? This was measured using ng-stats https://github.com/chrisprice/ng-stats.js/blob/master/ng-stats.js and running (new NgStats()).countWatchers(angular.element($0).scope()) on the ui-grid root element.

**Comment by PaulL1** [comment]
I think this was perhaps a defect in the scrolling code (that I introduced).  Could you try with unstable, there are some fixes that I pushed today that may resolve the issue.

Also, if you're very concerned with scroll performance, you could look at the 404 tutorial, which has two additional (expert user only) switches that reduce our lag on large data sets.

**Comment by axelnormand** [comment]
Hi @PaulL1 
I was also getting this with RC20. Have tried the latest unstable and am still see the blank space when scrolling using the sidebar.

**Comment by acheshire-scottlogic** [comment]
@PaulL1 
I tried the latest unstable version of ui-grid using the same data from the plnkr links in my first comment (http://plnkr.co/edit/UIwnxGfmeWm0amWrWI5R?p=preview). There is perhaps a slight improvement since RC-20 but it is still considerably worse than the example using RC-16.

Unfortunately, we can not use the switches mentioned in the 404 tutorial as we require the complex binding methods.

**Comment by c0bra** [comment]
@acheshire-scottlogic Any chance RC22 is any better?

**Comment by acheshire-scottlogic** [comment]
@c0bra There doesn't appear to be any performance improvement between RC-20 and RC-22.

**Comment by c0bra** [comment]
From looking at your plunker I don't think there's much we can do without a refactor of the scrolling code.

One thing that Telerik's Kendo Grid does is to remove visual scrolling past a certain scroll speed. So if the user starts scrolling > 20 rows / second (for instance), they lock the canvas in place and just swap out the row data. So it sorts "looks" like scrolling but no elements are actually moving around in space.

Then once the user slows down it will revert back to the normal scroll mode.

@acheshire-scottlogic @PaulL1 @swalters  Any thoughts on this? It would be an enhancement. There's not really anything "wrong" with our scrolling; you just can't render thousands of elements scrolling around in <1 second with Angular the way it is now.

**Comment by ima-tech** [comment]
I'm having the exact problem still on 3.0.6

**Comment by swalters** [comment]
closing this issue as there are many open issues relating to scrolling performance and it is a well-known issue
