### ISSUE TITLE
in 3.0.0-rc.21 stable, error on moving column

### ISSUE THREAD

**Issue by jibap** [angular-ui/ui-grid#3391]
3.0.0-rc.21 - Chrome
Bad effect when moving column, the clone go away on the right :
![image](https://cloud.githubusercontent.com/assets/3915029/7408276/79270b54-ef1b-11e4-8966-a9a2dcafee6c.png)
On this picture, my cursor is still on the "Hostname" column

The issue not appear on previous version

**Comment by xavifuefer** [comment]
Hi! any progress on this? I was about to have a look

**Comment by PaulL1** [comment]
There are a handful of issues on move columns that might all make sense to look at together.  Including #3356, and there's another one out there where the move column goes a bit crazy if you drag outside the grid then back inside again.

Feel free to take a go at it.

**Comment by AgDude** [comment]
I don't know if this is the same issue, but. opened pull request #3426 related to moving columns.

**Comment by cutterbl** [comment]
Any idea when #3426 might get pulled in? I verified that it does fix the placement of the dragged column header when using left pinned columns in the same configuration.

**Comment by AgDude** [comment]
That pull request was merged several weeks ago. There hasn't been an RC release in a while, so make sure you are using the "unstable" build.

**Comment by thomashilzendegen** [comment]
The problem startet with this commit: 1a83269a4b4e17f8593e50a3cae47825e69f2f64

Reverting .moveColumn to "position: absolute" fixes this somehow, but the side effect may be investigated regarding the IE fix introduced in that change.

**Comment by jibap** [comment]
I use now the last release (3.0.1) and it works for me, it was fixed ?

**Comment by thomashilzendegen** [comment]
No, it is still broken when horizontal scroll is possible.
But there seems a PR to address this: https://github.com/angular-ui/ui-grid/pull/3652

**Comment by swalters** [comment]
fixed in 3.1
