### ISSUE TITLE
Moving a column when the grid has horizontal scroll is somewhat broken

### ISSUE THREAD

**Issue by iorzetic** [angular-ui/ui-grid#3862]
When you try to move a column after horizontally scrolling all the way to the right (or somewhat to the right) produces very weird effects:
- the column header clone flies of to the left
- the grid appears to be scrolling at a very fast pace to the left (but probably due to the accelerating column header)
- the actual move of the column appears to be OK, it is only influenced a bit by the accelerating the column header clone (a bit = the fast scrolling of the grid prevents you from accurately move it)

Also, when you are scrolled to the left and try to move a column to the right after the first viewport width, the column header clone starts moving to the left once you hit the right margin.

I reproduced the bug here (move column example + extra columns + column size):
http://plnkr.co/edit/3tbbFWEYREK9vzo5ePba?p=preview

I tried to record a few seconds in the hope that the weird action will be more evident:
http://screencast.com/t/hXnAKOT2

**Comment by JLLeitschuh** [comment]
Duplicate of #3448

**Comment by iorzetic** [comment]
This not only a duplicate of #3448, it also contains other failure points.

**Comment by avinashhota** [comment]
Hi, Please let me know, when the fix for the below mentioned issue, would be release and in which version. Looking for a quick reply.

**Comment by swalters** [comment]
fixed in 3.1

**Comment by shaileshayer** [comment]
Movable columns in Horizantal scroll issue is still there in UI-Grid 3.2.1
