### ISSUE TITLE
Incorrect css link in the example

### ISSUE THREAD

**Issue by Leo-g** [angular-ui/ui-grid#4066]
I was trying the tutorial http://ui-grid.info/docs/#/tutorial/101_intro and I found the link to the css style sheet is not correct in the example
     
    <script src="/release/ui-grid.css"></script> 

Shouldn't it be ?
     
      <link rel="styleSheet" href="node_modules/angular-ui-grid/ui-grid.min.css"/>

Also the main.css file was not included in index.html

**Comment by Leo-g** [comment]
Also on the main site  http://ui-grid.info/ when I click on the tutorial button I get redirected to http://127.0.0.1:9003/docs/#/tutorial

**Comment by JLLeitschuh** [comment]
That is a known bug that should be fixed.

**Comment by ingshtrom** [comment]
1. It looks like this is prevalent across a lot of the tutorials. So a PR should fix all of those.
2. the link to the tutorials on the homepage links to http://ui-grid.info/docs/#/tutorial as expected. That must have been fixed in another PR.
3. I want to get started with UI-Grid and contributing (even the basics of PR's in GitHub), so I'll take this.

**Comment by ingshtrom** [comment]
One note: PR #4245 does not fix the css being loaded via script tags in all of the tutorial's source code.  I think I would need to create a PR on https://github.com/c0bra/grunt-ngdocs to fix that.

**Comment by c0bra** [comment]
`<script src="/release/ui-grid.css"></script>` is correct, it's a relative url to http://ui-grid.info/release/ui-grid.css
