### ISSUE TITLE
If we have a single digit page number displayed, then we can't use backspace key for removing the page number to enter a new one. There cannot be a state where we have an empty page number box. 

### ISSUE THREAD

**Issue by prakhar3agrwal** [angular-ui/ui-grid#4594]
The major problem here is that suppose we are at page 32 and we press backspace, then '2' is removed from '32' and page 3 is displayed. Now if we again press backspace then we are navigated to page '1' and '1' is displayed in the page number box. Now if we want to see page '9' then we will have to select '1' present in the page number box using shift key or using mouse and replace it with '9'. Backspace key is non-active here. Ideal way should be that if we press backspace then the page should not change and the page number box should become empty so that user can type any other page number.

Current functioning:
![initial](https://cloud.githubusercontent.com/assets/4592280/10816467/f0c1ac24-7e58-11e5-9f19-982236b1998e.jpg)

Expected functioning:
![expected](https://cloud.githubusercontent.com/assets/4592280/10816479/fd99055a-7e58-11e5-9f18-967efab5de37.jpg)

I have made the solution for it and will be submitting the pull request soon. Please review the issue.

**Comment by AnirudhaGohokar** [comment]
Hi @prakhar3agrwal ,

Were you able to submit PR.

Though I have fixed the issue by changing line no:21327 to this:

```
if (!angular.isNumber(options.paginationCurrentPage) || options.paginationCurrentPage < 1) {
    //options.paginationCurrentPage = 1; original code to reset page number
    if(options.paginationCurrentPage===undefined)
        options.paginationCurrentPage = undefined;
    else
        options.paginationCurrentPage = $scope.paginationApi.getTotalPages();
     return;
}

```

This also fixes another issue with ui grid were if you are on the second last page and change the pagination size it will reset to 1st page and not the current page.

Thanks,
Anirudha

**Comment by prakhar3agrwal** [comment]
Hi Anirudha,

No I was not able to submit PR, it's good that the issue is fixed. However
it would be great if  my PR is accepted so that I can fix issues in future.

Regards,
Prakhar

On Mon, May 16, 2016 at 12:08 PM, Anirudha Gohokar <notifications@github.com

**Comment by AnirudhaGohokar** [comment]
@prakhar3agrwal apparently that didn't fix the issue..so have updated the comment to pinpoint the cause behind it. Will require some logical change and a lot of testing there.

**Comment by orneryd** [comment]
Thanks for contributing! This repository has been transferred, and we're preparing the new 5.x release. We're closing older issues and pull requests as part of the reset. Please join us on Discord to follow the work or continue the conversation: https://discord.gg/Baz4w8ZWN
