### ISSUE TITLE
Support Angular 1.5.0

### ISSUE THREAD

**Issue by PierrePIRONIN** [angular-ui/ui-grid#5070]
Hi, 
What about support Angular [1.5.0](https://github.com/angular/angular.js/releases/tag/v1.5.0) released on February 5, 2016  ?

**Comment by JLLeitschuh** [comment]
Everything should work for angular 1.5
Our test system doesn't use 1.5 yet but it will when we drop support for earlier versions of angular.
https://github.com/angular-ui/ui-grid/pull/5086/files

**Comment by PierrePIRONIN** [comment]
Ok, thanks !

**Comment by victordelacruz** [comment]
I updated an application from angular 1.4.3 and ui-grid 3.0.7 to angular 1.5.0 and ui-grid 3.1.1 and it stopped working.

I'm getting some errors on methods that fetch some grid properties from the grid API, because they are being called before the onRegisterApi kicks off.

**Comment by billyaraujo** [comment]
+1

**Comment by jjmontesl** [comment]
+1 Also, bower package seems to be constraining the version: `bower angular#>=1.2.16 1.4.x`

**Comment by streetcore** [comment]
+1

**Comment by taufanardi** [comment]
+1

**Comment by lobo-tuerto** [comment]
+1

**Comment by MooDySmiles** [comment]
+1

**Comment by kinnrot** [comment]
+1

**Comment by dangribbin** [comment]
+1

**Comment by Fost** [comment]
++

**Comment by ritter** [comment]
+1

**Comment by mole-chen** [comment]
+1

**Comment by savokiss** [comment]
+1

**Comment by ravitejadeevi** [comment]
+1

**Comment by aplocher** [comment]
+1

**Comment by brettjacobson** [comment]
+1

**Comment by carolynyoo** [comment]
+1

**Comment by guilherme6191** [comment]
Is there any workaround for the  bower package constraint?

**Comment by vadivelm85** [comment]
+1

**Comment by el-davo** [comment]
+1

**Comment by thanateros** [comment]
+50.  Boggles my mind to see a stable version out so long and one of its own support libraries can't even keep up.  The lack of an angular-native grid that keeps up with the current stable release is keeping my organization from adopting angular.  Would be cool if this *glaring* coffee-stain could be removed.

**Comment by andertun** [comment]
+1

**Comment by waynebloss** [comment]
Anyone here tried it yet? Just asking since the very first reply says "Everything should work for angular 1.5".

I just built an angular 1.5 app and dropped ui-grid into it, tried a few things and it does indeed seem like everything is working in 1.5.

This is open source - if you're letting something like this stop you from moving forward with angular 1, in 2016, then you're doing it wrong.

**Comment by el-davo** [comment]
We are using it. Works fine with angular 1.5 for us. So far no issues

**Comment by bjaraujo** [comment]
@waynebloss  Everything seems to be working for me too. 

But bower file of the latest release marks it as not compatible with 1.5.

**Comment by scicompth** [comment]
We happened to test our app with 1.5.7 and didn't notice issues. 
But, https://github.com/angular-ui/ui-grid says : 1.4.x 

 Is there anything we should be worried off ?

**Comment by timothyswt** [comment]
This might be due to angular.js bugs introduced in the 1.5.x branch related to ng-bind-html or $compile or any number of other broken functionality fixed in 1.5.6. If that is the case, you should be able to safely use 1.5.6 or greater.

https://github.com/angular/angular.js/blob/master/CHANGELOG.md

**Comment by akeucon** [comment]
I read here that it works but still showing not with 1.5or higher?
How did u get it then to run with gridApi?
It throw me an error allways
http://plnkr.co/edit/wJKwbgvWAcIFiPR6z5oT?p=info
if someone can just check and help me pls

**Comment by antoine42** [comment]
I just tried ui-grid 3.0.0-RC.22 with angular 1.5.8 and no issues so far.
Is there any plan to support 1.5.x officially?

**Comment by JLLeitschuh** [comment]
> +50. Boggles my mind to see a stable version out so long and one of its own support libraries can't even keep up. The lack of an angular-native grid that keeps up with the current stable release is keeping my organization from adopting angular. Would be cool if this glaring coffee-stain could be removed.
> \-@thanateros

There's a great line in open source, it's **Free as in Puppy**.

This project is not maintained by the angular team. This is an independent project with independent developers. We all work on our own time. None of us are paid for this work.
I'm no longer maintaining this project as I have changed companies and I'm working in a different layer of the software stack.
We are always looking for new developers who are interested in maintaining UI-Grid.
Message me privately on gitter if you are interested in becoming a maintainer.

If your company has a vested interest in this software then consider discussing with your managers dedicating some resources to improving UI-Grid.

I began working on this project here: https://github.com/angular-ui/ui-grid/pull/5086
I don't have the time to finish resolving that PR. If someone would like to merge up my work to master and submit a new PR that would be useful.

**Comment by stadler** [comment]
+1

**Comment by CyborgMaster** [comment]
Would it be possible to simply relax the limitations in bower.json from `>=1.2.16 1.4.x` to `>=1.2.16 1.5.x`.  It seems like there are at least several people using this successfully with Angular 1.5.  I'm not asking for complete support, just an easier way to experiment.  It's unfortunate that I have to fork the project just to relax the version constraints.  

Thanks and great work!

**Comment by abumere** [comment]
@CyborgMaster Hey I am working on a side project myself really want to use this tool. Can you explain the steps taken to relax or update the version constraints?

**Comment by CyborgMaster** [comment]
You can simply fork the project on github, modify the bower.json file and then modify your project's bower.json file to point to your github repo.

**Comment by mportuga** [comment]
Version 1.5.x is already supported by UI-grid on the latest version.
