### ISSUE TITLE
Fonts references in css not found in v3.2.10

### ISSUE THREAD

**Issue by eugenehuanggy** [angular-ui/ui-grid#6130]
- [1] This is a bug report, not a question on how to use the grid.  
- [2] You have searched the open issues to see if this bug has been filed before.  We don't want duplicate issues.

I've isolated that the issue to the following commit: (https://github.com/angular-ui/ui-grid/commit/f81e888a0b157d9760a7e7272304c6f383139c8a)

`Fontello.eot` should be renamed to `ui-grid.eot` as defined in `src/less/icons.less`

**Comment by st2rseeker** [comment]
I second the issue - didn't check the cause, but sounds probable (in my case 3.2.9 -> 3.2.10 makes the V selection icons in the grid to disappear)

**Comment by mportuga** [comment]
I am on it

**Comment by mportuga** [comment]
Issue will be resolved by this commit: https://github.com/angular-ui/ui-grid/commit/53b9e33a8771a81e86d0d56b38a1eb6cd880c230

**Comment by mportuga** [comment]
This issue has been resolved in version 3.2.11

**Comment by xReeQz** [comment]
I have 3.2.11 installed via bower - the issue is still there.

**Comment by sunscheung** [comment]
I have 3.2.11 installed via npm - the issue is still there. @mportuga
