### ISSUE TITLE
rtl support in Chrome

### ISSUE THREAD

**Issue by mahdiprog** [angular-ui/ui-grid#6193]
Hi
when the grid has scroll in RTL and in Google Chrome there is issues:
 - when you scroll vertically rows disappears 
 - when you scroll horizontally headers stick to left and columns scroll
but there is not a problem in Firefox
also column menu position is false (both Chrome and Firefox)
you can check it in tutorial: [RTL Support](http://ui-grid.info/docs/#/tutorial/120_RTL)

**Comment by hamed-vojdani** [comment]
hi, I have this issue too, does anyone have a workaround? please

**Comment by hamed-vojdani** [comment]
chrome 58 bug for scrolleft calculation
https://bugs.chromium.org/p/chromium/issues/detail?id=720227

as temprory solution for chrome 58 change put this hack after line 11562 of ui-grid.js

```
 //chrome 58 bug resolve
    var is_chrome = /chrome/i.test(navigator.userAgent);
    if (is_chrome) {
        type = "dafault";
    }
```

**Comment by DmitryVovchuk** [comment]
This workaround doesn't works for me.Is anyone got it works inRTL???

**Comment by hamed-vojdani** [comment]
Found Solution, ui-gird used this library codes for detect rtl scroll type:
https://github.com/othree/jquery.rtl-scroll-type

library code changed 2 month ago, please  update codes used from this library, every thing will be fine

line 11546 
old code:
` var definer = angular.element('<div dir="rtl" style="font-size: 14px; width: 1px; height: 1px; position: absolute; top: -1000px; overflow: scroll">A</div>')[0],`

new code:
`var definer = angular.element('<div dir="rtl" style="font-size: 14px; width: 4px; height: 1px; position: absolute; top: -1000px; overflow: scroll">ABCD</div>').appendTo('body')[0],`

**Comment by DmitryVovchuk** [comment]
This solution works well for me 
thank you

**Comment by hamed-vojdani** [comment]
problem solved in chorme 60 and earlier.

**Comment by mozaffar** [comment]
I have chrome 75 and the problem is still there. The solution is very simple:
add following style to your project css file:
```css
.ui-grid-header-cell-row{
    position: sticky;
    right: 0;
}
```

**Comment by hvojdani** [comment]
> Found Solution, ui-gird used this library codes for detect rtl scroll type:
> https://github.com/othree/jquery.rtl-scroll-type
> 
> this library codes changed 2 month ago, please update codes used from this library, every thing will be fine
> 
> line 11546 in ui-grid.js
> old code:
> ` var definer = angular.element('<div dir="rtl" style="font-size: 14px; width: 1px; height: 1px; position: absolute; top: -1000px; overflow: scroll">A</div>')[0],`
> 
> new code:
> `var definer = angular.element('<div dir="rtl" style="font-size: 14px; width: 4px; height: 1px; position: absolute; top: -1000px; overflow: scroll">ABCD</div>').appendTo('body')[0],`

I am currently using this fix and no problem. The root cause is wrong calculation of right to left type.

 @mozaffar the problem exists after adding your style with chrome dev tools in this page:
[http://ui-grid.info/docs/#!/tutorial/Tutorial:%20120%20RTL%20Support](url)

**Comment by tomyam1** [comment]
None of the solution proposed here worked for me.

The solution by [hvojdani](https://github.com/angular-ui/ui-grid/issues/6193#issuecomment-307549980) is no longer needed since RTL scrollLeft [type](https://github.com/othree/jquery.rtl-scroll-type) is now detected correctly in Chrome.

The soltion by [mozaffar](https://github.com/angular-ui/ui-grid/issues/6193#issuecomment-501596940) make things better in Chrome (still not perfect aliment) but worsened the situation on Firefox.

The following solution worked for me on all browsers:

@hvojdani @mozaffar can you give it a try?

```js
app.run(function ($templateCache) {
  $templateCache.put('ui-grid/ui-grid-header',
    '<div role="rowgroup" class="ui-grid-header"><!-- theader --><div class="ui-grid-top-panel"><div class="ui-grid-header-viewport"><div class="ui-grid-header-canvas"><div class="ui-grid-header-cell-wrapper"><div class="ui-grid-header-viewport-padding" ng-style="colContainer.headerCellWrapperStyle()"><div role="row" class="ui-grid-header-cell-row"><div class="ui-grid-header-cell ui-grid-clearfix" ng-repeat="col in colContainer.renderedColumns track by col.uid" ui-grid-header-cell col="col" render-index="$index"></div></div></div></div></div></div></div>'
  );
});
```
It moves the margin from the `.ui-grid-header-cell-wrapper` element to a new `.ui-grid-header-viewport-padding` element.

It fixes the RTL issues with Chrome and Safrai (IE and Firefox worked fine before and works fine now).

http://plnkr.co/edit/pi0qI8opO7qJkaQoZz0p

### Chrome 76

Before fix:

![image](https://user-images.githubusercontent.com/3265649/62659216-719cf480-b973-11e9-8fb5-e1e396408b62.png)

After Fix:

![image](https://user-images.githubusercontent.com/3265649/62659196-6053e800-b973-11e9-810f-aaa9cf791569.png)

### Safari

Before fix:

![image](https://user-images.githubusercontent.com/3265649/62659378-dfe1b700-b973-11e9-948a-b0f889d4fd06.png)

After fix:

![image](https://user-images.githubusercontent.com/3265649/62659304-a6a94700-b973-11e9-8623-3eb52a56dfc8.png)

**Comment by orneryd** [comment]
Thanks for contributing! This repository has been transferred, and we're preparing the new 5.x release. We're closing older issues and pull requests as part of the reset. Please join us on Discord to follow the work or continue the conversation: https://discord.gg/Baz4w8ZWN
