### ISSUE TITLE
Scrollbar issue in version 4.3

### ISSUE THREAD

**Issue by achenxp** [angular-ui/ui-grid#6280]
When a column is pinned with no horizontal scrollbar showing for unpinned columns, the pinned column still shows scrollbar placeholder which makes the grid look odd. http://plnkr.co/edit/kRAvZljoYqyX4QiHe2Vh?p=preview

**Comment by lenkaK** [comment]
Problem is in ui-grid.js. 
`styles['overflow-x'] = self.hasHScrollbar ? 'auto' : 'hidden';`. In previous version of ui-grid there was 'scroll' instead of 'auto'.

**Comment by MatejQ** [comment]
+1 for a fix

**Comment by cybermerlin** [comment]
i have fixed in
https://github.com/cybermerlin/ui-grid/tree/develop

**Comment by achenxp** [comment]
Still doesn't look right with WHEN_NEEDED option specified while horizontal scrollbar is showing with pinned column. Scroll to the bottom, and you'll see the rows are not aligned between pinned and unpinned columns.
http://plnkr.co/edit/zHldTgH6BFK9lOu4cgIq?p=preview
