### ISSUE TITLE
http://ui-grid.info/customizer does not work

### ISSUE THREAD

**Issue by sjoerd222888** [angular-ui/ui-grid#6305]
Customizer on website does not work.

http://ui-grid.info/customizer just shows

{{ cssErr }}

**Comment by zackurben** [comment]
Hey @sjoerd222888 the correct url is: `http://ui-grid.info/customizer/`, note the trailing `/`.

I fixed one link to the wrong page with: https://github.com/angular-ui/ui-grid/pull/6282. Did you happen to find another?

**Comment by sjoerd222888** [comment]
I used the link on the front page on the left-hand side of the front page, url: `http://ui-grid.info`. There it seems the link is still wrong.

The inspector yields the following HTML for the link: `<a href="/customizer">customizer</a>`
